"""Digest-bound approval and executable pytest/JSON export."""
from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

from .models import Approval, RegressionProposal


def proposal_digest(proposal: RegressionProposal) -> str:
    payload = proposal.model_dump(mode="json", exclude={"digest", "reviewed", "approval_digest", "approved_by", "approved_at"})
    return hashlib.sha256(json.dumps(payload, sort_keys=True, separators=(",", ":")).encode()).hexdigest()


def prepare_proposal(title: str, rationale: str, tests: list[dict[str, Any]], source_trial_ids: list[str]) -> RegressionProposal:
    proposal = RegressionProposal(title=title, rationale=rationale, tests=tests, source_trial_ids=source_trial_ids)
    proposal.digest = proposal_digest(proposal)
    return proposal


def approve(proposal: RegressionProposal, approver: str) -> Approval:
    digest = proposal_digest(proposal)
    if not proposal.digest or proposal.digest != digest:
        raise ValueError("proposal digest is stale")
    proposal.reviewed = True
    proposal.approval_digest = digest
    proposal.approved_by = approver
    approval = Approval(proposal_digest=digest, approved_by=approver)
    proposal.approved_at = approval.approved_at
    return approval


def export_proposal(proposal: RegressionProposal, approval: Approval, directory: str | Path) -> tuple[Path, Path]:
    digest = proposal_digest(proposal)
    if not proposal.reviewed or proposal.digest != digest or proposal.approval_digest != digest or approval.proposal_digest != digest:
        raise PermissionError("explicit approval for current proposal digest is required")
    directory = Path(directory)
    directory.mkdir(parents=True, exist_ok=True)
    json_path = directory / "regression-proposal.json"
    test_path = directory / "test_faultline_regression.py"
    json_path.write_text(json.dumps(proposal.model_dump(mode="json"), indent=2), encoding="utf-8")
    test_path.write_text(_pytest_source(proposal), encoding="utf-8")
    return test_path, json_path


def _pytest_source(proposal: RegressionProposal) -> str:
    cases: list[dict[str, Any]] = []
    for test in proposal.tests:
        cases.extend(test.get("cases", []))
    # Observed violations remain evidence metadata. Expected future behavior is
    # always the independently reviewed checker result and eligibility rule.
    return '''"""Generated by Faultline after human approval.\n\nThe test invokes the configured application now; it never trusts saved outputs.\n"""\nimport os\nimport pytest\nfrom faultline.models import Scenario\n\n\ndef _application():\n    target = os.getenv("FAULTLINE_LIVE_TARGET")\n    if not target:\n        pytest.skip("FAULTLINE_LIVE_TARGET is not configured; refusing fake pass")\n    from faultline.adapters import load_configured_target\n    return load_configured_target(target)\n\n\ndef test_reviewed_regression_cases():\n    app = _application()\n    cases = %r\n    if not cases:\n        pytest.skip("proposal contains no executable cases")\n    for case in cases:\n        scenario = Scenario.model_validate(case["scenario"])\n        run = app.run(scenario)\n        assert run.checker_status == "completed"\n        assert run.checker_passed is True\n        assert (run.agent_action is not None and run.agent_action.kind == "refund") is bool(case["expected_eligible"])\n''' % cases
