"""Digest-bound approval and executable pytest/JSON export."""
from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

from .models import Approval, RegressionProposal


def proposal_digest(proposal: RegressionProposal) -> str:
    payload = proposal.model_dump(mode="json", exclude={"digest", "reviewed", "approval_digest", "approved_by", "approved_at"})
    return hashlib.sha256(json.dumps(payload, sort_keys=True, separators=(",", ":")).encode()).hexdigest()


def prepare_proposal(title: str, rationale: str, tests: list[dict[str, Any]], source_trial_ids: list[str]) -> RegressionProposal:
    proposal = RegressionProposal(title=title, rationale=rationale, tests=tests, source_trial_ids=source_trial_ids)
    proposal.digest = proposal_digest(proposal)
    return proposal


def approve(proposal: RegressionProposal, approver: str) -> Approval:
    digest = proposal_digest(proposal)
    if not proposal.digest or proposal.digest != digest:
        raise ValueError("proposal digest is stale")
    proposal.reviewed = True
    proposal.approval_digest = digest
    proposal.approved_by = approver
    approval = Approval(proposal_digest=digest, approved_by=approver)
    proposal.approved_at = approval.approved_at
    return approval


def export_proposal(proposal: RegressionProposal, approval: Approval, directory: str | Path) -> tuple[Path, Path]:
    digest = proposal_digest(proposal)
    if not proposal.reviewed or proposal.digest != digest or proposal.approval_digest != digest or approval.proposal_digest != digest:
        raise PermissionError("explicit approval for current proposal digest is required")
    directory = Path(directory)
    directory.mkdir(parents=True, exist_ok=True)
    json_path = directory / "regression-proposal.json"
    test_path = directory / "test_faultline_regression.py"
    json_path.write_text(json.dumps(proposal.model_dump(mode="json"), indent=2), encoding="utf-8")
    test_path.write_text(_pytest_source(proposal), encoding="utf-8")
    return test_path, json_path


def _pytest_source(proposal: RegressionProposal) -> str:
    cases: list[dict[str, Any]] = []
    for test in proposal.tests:
        cases.extend(test.get("cases", []))
    # The generated test intentionally executes the current configured
    # application. Stored run outcomes are evidence metadata, never a pass.
    source = '''"""Generated by Faultline after human approval.

The test invokes the configured current application; it never trusts saved outputs.
"""
import os
import pytest
from faultline.models import Scenario

PROPOSAL_DIGEST = "__DIGEST__"


def _application(configuration_id, case_id):
    target = os.getenv("FAULTLINE_LIVE_TARGET")
    if not target:
        pytest.skip("FAULTLINE_LIVE_TARGET is not configured; refusing fake pass")
    from faultline.adapters import load_configured_target
    from faultline.budget import open_canonical_ledger
    # Exported tests always use the process-wide canonical ledger, regardless
    # of the directory that contains this generated file.
    ledger = open_canonical_ledger(ceiling_usd=10.0, automation_cap_usd=2.0, case_cap_usd=1.0)
    return load_configured_target(target, budget=ledger, case_id=case_id)


def test_reviewed_regression_cases():
    cases = __CASES__
    if not cases:
        pytest.skip("proposal contains no executable cases")
    # One stable case identity shares the per-case budget across every
    # configuration row in this export execution.
    export_case_id = "export:" + PROPOSAL_DIGEST
    applications = {}
    for case in cases:
        configuration_id = case.get("configuration_id", "default")
        if configuration_id not in applications:
            applications[configuration_id] = _application(configuration_id, export_case_id)
        app = applications[configuration_id]
        scenario = Scenario.model_validate(case["scenario"])
        run = app.run(scenario, configuration_id=configuration_id)
        assert run.checker_status == "completed"
        assert run.checker_passed is True
        assert (run.agent_action is not None and run.agent_action.kind == "refund") is bool(case["expected_eligible"])
'''
    return source.replace("__CASES__", repr(cases)).replace("__DIGEST__", proposal.digest)
